- name: demo on variables
  hosts: localhost
  connection: local
  vars:
    COURSE: "DevSecOps" 
    DURATION: "4-Months"
    TRAINER: "SivaKumar"
    NAME: "Harsha D"
  tasks:
    - name: printing variables
      vars:
         COURSE: "DevSecOps with AIOPS"
      debug:
        msg: "Hey, I am {{NAME}} , i ma  practicing  {{ COURSE }} course, and the Duration is {{ DURATION }}, and trainer is {{ TRAINER }}, common_key:{{common_key}}"
