- name: demo on variables
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
    - name: printing variables
      debug:
        msg: "Hey, I am {{ Course }} practicing variables in ansible, and the Duration is {{ Duration }}, and trainer is {{ Trainer }}"
