- name: demo on variables
  hosts: localhost
  connection: local
  vars:
     Course: "DevSecOps"
     Duration: "4-Months"
     Trainer: "SivaKumar"
  tasks:
   - debug:
       msg: "Hey , I am practicing variables in ansible, "