- name: demo on variables
  hosts: frontend
  tasks:
   - name: printing variables
     debug:
        msg: "Executing the Frontend module"
     debug:   
        msg: "Hey, I am {{ Course }} practicing variables in ansible, and the Duration is {{ Duration }}, and trainer is {{ Trainer }}"



# variables on inventory files 


- name: demo on variables
  hosts: local
  connection: local
  tasks:
   - name: printing variables
     debug:
        msg: "Executing the local module"
     debug:   
        msg: "Hey, I am {{ Course }} practicing variables in ansible, and the Duration is {{ Duration }}, and trainer is {{ Trainer }}"
