- name: demo on variables
  hosts: frontend
  tasks:
   - name: printing information
     debug:
      msg: "Hey, I am {{NAME}} , i ma  practicing  {{ COURSE }} course, and the Duration is {{ DURATION }}, and trainer is {{ TRAINER }}"
