- name: conditinoss
  hosts: local
  connection: local
  vars:
     devops_live_sessions : 7
  tasks:
   - name: devops session more than 5 
     debug:
       msg:  "Yes ansible done more than 5 sessinos"
     when: devops_live_sessions > 5
    