- name: Demo on Functions
  hosts: frontend
  vars:
    topics: Linux, Ansible, Terraform, Git, ShellScript
    TagMap:
       name: Ansible
       project: Roboshop
       environment: Development
  tasks:
   - name: converting string to list
     debug:
       msg: "Topics are : {{ topics | split (',')  }}"
 