- name: Demo on Functions
  hosts: frontend
  vars:
    topics: Linux, Ansible, Terraform, Git, ShellScript
    TagMap:
       name: Ansible
       project: Roboshop
       environment: Development
    tagsList:  [
        {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "Roboshop"
        },
        {
            "key": "environment",
            "value": "Development"
        }
    ]
    full_name: dasari harshavardhan 
    full_name1: DASARI HARSHAVARDHAN

    ip_address: 132.34.5.33
  tasks:
   - name: converting string to list   #converting string to list
     debug:
       msg: "Topics are : {{ topics | split (',')  }}"

   - name: set as a default values    # setting as default value 
     debug:
       msg: "Hi  {{ GREETING | default ('hello , i am default to print this msg')  }}"
 
   - name: convert to map to list   # coverting map to list
     debug:
       msg:  "{{ TagMap | dict2items }}"

   - name: convert to list to map  # converting list to map
     debug:
       msg:  "{{ tagsList | items2dict }}"

   - name: convert to uppercase
     debug:
       msg : "{{full_name | upper}} "

   - name: convert to lowercase
     debug:
       msg : "{{full_name1 | lower}} "

   - name: validate ip address
     debug:
       msg : "{{ip_address | ansible.utils.ipv4 }} "
      
   
    




