[frontend]
54.144.243.189 Course= "Ansible for node-1" 
52.91.54.71    Course= "Ansible for node-2" 

[catalogue]
13.218.124.145

[cart]
13.218.124.146

[user]
13.218.124.147

# ;group of groups
# [roboshop:children]
# frontend
# catalogue
# cart
# user

[local]
localhost

[local:vars]
COURSE= "DevSecOps" 
DURATION= "4-Months"
TRAINER= "SivaKumar"
NAME= "Harshavardhan"


[frontend:vars]
COURSE= "DevSecOps" 
DURATION= "4-Months"
TRAINER= "SivaKumar"
NAME= "Harshavardhan"